version: '2'
  
services:
 db:
   image: mysql
   environment:
     - MYSQL_ROOT_PASSWORD=my-secret-pw
   volumes:
     - mysql_volume:/var/lib/mysql

 phpmyadmin:
   image: phpmyadmin/phpmyadmin
   ports:
     - 8080:80
   environment:
     - MYSQL_ROOT_PASSWORD=my-secret-pw
 php:
   image: php:7.1-apache
   ports:
     - 80:80
volumes:
   mysql_volume:

