version: '2'
  
services:
 mysql:
   image: mysql
   container_name: mysql
   environment:
     - MYSQL_ROOT_PASSWORD=my-secret-pw
   volumes:
     - mysql_volume:/var/lib/mysql

 phpmyadmin:
   image: phpmyadmin/phpmyadmin
   container_name: phpmyadmin
   ports:
     - 8080:80
   environment:
     - MYSQL_ROOT_PASSWORD=my-secret-pw
     - PMA_HOST=mysql
   depends_on:
     - mysql

 php:
   image: php:7.1-apache
   container_name: php
   ports:
     - 80:80
   environment:
     - MYSQL_ROOT_PASSWORD=my-secret-pw
     - PMA_HOST=mysql
   depends_on:
     - mysql
# notes this volume does NOT need to be the same as that used for mysql, but I can name it to eventually share it with other contianers
   volumes:
     - php:/var/html/htdocs


# note if you are using named volumes, it is required that it is listed also below
volumes:
   mysql_volume:
   php:

