version: '2'
  
services:
 mysql:
   image: mysql
   container_name: mysql
   environment:
     - MYSQL_ROOT_PASSWORD=my-secret-pw
   volumes:
     - mysql_volume:/var/lib/mysql

 phpmyadmin:
   image: phpmyadmin/phpmyadmin
   container_name: phpmyadmin
   ports:
     - 8080:80
   environment:
     - MYSQL_ROOT_PASSWORD=my-secret-pw
     - PMA_HOST=mysql
   depends_on:
     - mysql

volumes:
   mysql_volume:

